version: '3'

env:
  PUID:
    sh: id -u
  PGID:
    sh: id -g
  
dotenv: ['.env']
  
tasks:
  hello:
    desc: Hello world task
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  list:
    desc: List all tasks
    cmds:
    - task --list
    silent: true

  build:
    desc: Build Firecracker image in current directory
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f build.sh
    silent: true
    cmds:
    - pwd
    - "[ -d output ] || mkdir output"
    - chmod +x build.sh
    - ./build.sh

  test:
    desc: Test Firecracker image in current directory (no persistence/network)
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f config.json
    silent: true
    cmds:
    - firecracker --no-api --config-file config.json