version: '3'

env:
  PUID:
    sh: id -u
  PGID:
    sh: id -g
  
dotenv: ['.env']
  
tasks:
  hello:
    desc: Hello world task
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  list:
    desc: List all tasks
    cmds:
    - task --list
    silent: true

  build:
    desc: Build Firecracker rootfs image
    dir: rootfs
    preconditions:
      - test -f build.sh
    silent: true
    requires:
      vars: [ IMAGE, VERSION ]
    cmds:
    - pwd
    - "[ -d output ] || mkdir output"
    - chmod +x build.sh
    - "./build.sh {{ .IMAGE }} {{ .VERSION }}"

  test:
    desc: Test Firecracker image (no persistence/network)
    dir: rootfs
    preconditions:
      - test -f config.json
    silent: true
    requires:
      vars: [ IMAGE, VERSION ]
    cmds:
    - sed -i "s:output/.*\.img:output/{{ .IMAGE }}-{{ .VERSION }}.img:g" config.json
    - firecracker --no-api --config-file config.json

  deploy:
    desc: Deploy Firecracker squashfs image to server
    dir: rootfs/output
    silent: true
    requires:
      vars: [ IMAGE, VERSION ]
    preconditions:
      - test -f {{ .IMAGE }}-{{ .VERSION }}.img
    cmds:
    - sudo umount /mnt/firecracker || true
    - sudo rm -rf /mnt/firecracker
    - sudo mkdir -p /mnt/firecracker
    - sudo mount -t cifs -o guest //firecracker/rootfs /mnt/firecracker
    - sudo cp -f {{ .IMAGE }}-{{ .VERSION }}.img /mnt/firecracker/

  b-t:
    desc: Build and test Firecracker image
    aliases:
      - build-test
      - bt
    silent: true
    requires:
      vars: [ IMAGE, VERSION ]
    cmds:
    - task: build
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }
    - task: test
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }

  b-t-d:
    desc: Build, test and deploy Firecracker image
    aliases:
      - build-test-deploy
      - btd
    silent: true
    requires:
      vars: [ IMAGE, VERSION ]
    cmds:
    - task: build
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }
    - task: test
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }
    - task: deploy
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }

  b-d:
    aliases:
      - build-deploy
      - bd
    desc: Build and deploy Firecracker image
    silent: true
    requires:
      vars: [ IMAGE, VERSION ]
    cmds:
    - task: build
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }
    - task: deploy
      vars: { IMAGE: '{{ .IMAGE }}', VERSION: '{{ .VERSION }}' }

  talos:
    desc: Obtain Talos images for Firecracker and deploy to server
    silent: true
    requires:
      vars: [ VERSION ]
    cmds:
    # TODO: get latest patch for minor version given
    - mkdir -p rootfs/output
    - echo "Downloading initramfs"
    - curl -o  rootfs/output/talos-{{ .VERSION }}.xz -L https://github.com/siderolabs/talos/releases/download/v{{ .VERSION }}/initramfs-amd64.xz
    - mkdir -p kernel
    - echo "Downloading compressed kernel"
    - curl -o  kernel/vmlinuz-talos-{{ .VERSION }}.bin -L https://github.com/siderolabs/talos/releases/download/v{{ .VERSION }}/vmlinuz-amd64
    - echo "Uncompressing kernel"
    - extract-vmlinux kernel/vmlinuz-talos-{{ .VERSION }}.bin > kernel/vmlinux-talos-{{ .VERSION }}.bin
    - echo "Deploying initramfs to server"
    - sudo umount /mnt/firecracker || true
    - sudo rm -rf /mnt/firecracker
    - sudo mkdir -p /mnt/firecracker
    - sudo mount -t cifs -o guest //firecracker/rootfs /mnt/firecracker
    - sudo cp -f rootfs/output/talos-{{ .VERSION }}.xz /mnt/firecracker/
    - sudo umount /mnt/firecracker || true
    - echo "Deploying kernel to server"
    - sudo mount -t cifs -o guest //firecracker/kernel /mnt/firecracker
    - sudo cp -f kernel/vmlinux-talos-{{ .VERSION }}.bin /mnt/firecracker/
    - sudo umount /mnt/firecracker || true

